_target_: diffusion_policy.workspace.train_diffusion_unet_lowdim_workspace.TrainDiffusionUnetLowdimWorkspace
action_dim: 3
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-val_loss={val_loss:.3f}.ckpt
    k: 3
    mode: min
    monitor_key: val_loss
dataloader:
  batch_size: 400
  num_workers: 1
  persistent_workers: false
  pin_memory: true
  shuffle: true
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: default
horizon: 276
keypoint_dim: 2
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  # mode: disabled
  mode: online
  name: mstep_diffusion_random_push
  project: diffusion_policy_debug
  entity: anqiaoli
  resume: true
  tags:
  - mstep
  - random_push
  - only_one_direction
multi_run:
  run_dir: data/outputs/2023.01.16/20.10.02_train_diffusion_unet_lowdim_slipperness
  wandb_name_base: 2023.01.16-20.10.02_train_diffusion_unet_lowdim_slipperness
n_action_steps: 251
n_latency_steps: 0
n_obs_steps: 25
name: train_diffusion_unet_lowdim
obs_as_global_cond: true
obs_as_local_cond: false
obs_dim: 34
optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-06
past_action_visible: false
policy:
  _target_: diffusion_policy.policy.diffusion_unet_lowdim_policy.DiffusionUnetLowdimPolicy
  action_dim: 3
  horizon: 276
  mstep_prediction: true
  model:
    _target_: diffusion_policy.model.diffusion.conditional_unet1d.ConditionalUnet1D
    mrollouts: true
    horizon: 276
    cond_predict_scale: true
    diffusion_step_embed_dim: 256
    down_dims:
    - 256
    - 512
    - 1024
    global_cond_dim: 1678
    input_dim: 3
    kernel_size: 5
    local_cond_dim: null
    n_groups: 8
  n_action_steps: 251
  n_obs_steps: 25
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    beta_start: 0.0001
    clip_sample: true
    num_train_timesteps: 500
    prediction_type: epsilon
    variance_type: fixed_small
  num_inference_steps: 50
  oa_step_convention: true
  obs_as_global_cond: true
  obs_as_local_cond: false
  obs_dim: 34
  pred_action_steps_only: false
pred_action_steps_only: false
task:
  action_dim: 3
  dataset:
    _target_: diffusion_policy.dataset.random_push_mrollout_dataset.SlippernessLowdimDataset
    horizon: 276
    max_train_episodes: 50
    pad_after: 0
    pad_before: 0
    seed: 42
    val_ratio: 0.02
    zarr_path: /media/anqiao/My Passport/SP/Data/traj_data_random_push_003_command/traj.zarr
  env_runner:
    _target_: diffusion_policy.env_runner.pusht_keypoints_runner.PushTKeypointsRunner
    agent_keypoints: false
    fps: 10
    keypoint_visible_rate: 1.0
    legacy_test: true
    max_steps: 300
    n_action_steps: 8
    n_envs: null
    n_latency_steps: 0
    n_obs_steps: 2
    n_test: 50
    n_test_vis: 4
    n_train: 6
    n_train_vis: 2
    past_action: false
    test_start_seed: 100000
    train_start_seed: 0
  keypoint_dim: 2
  name: slipperness
  obs_dim: 34
task_name: slipperness_lowdim
training:
  checkpoint_every: 20
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 100
  resume: false
  resume_checkpoint_dir: /media/anqiao/My Passport/SP-checkpoitns/2023.11.21/02.30.44_train_diffusion_unet_lowdim_slipperness_lowdim
  rollout_every: 20
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 1
val_dataloader:
  batch_size: 1024
  num_workers: 1
  persistent_workers: false
  pin_memory: true
  shuffle: false
